const MODELS = {
  LOAD: 'MODEL_LOAD',
  LOAD_OK: 'MODEL_LOAD_OK',
  LOAD_FAILED: 'MODEL_LOAD_FAILED',
  SAVE: 'MODEL_SAVE',
  SAVE_OK: 'MODEL_SAVE_OK',
  SAVE_FAILED: 'MODEL_SAVE_FAILED',
  IMPORT_MODEL: 'MODEL_IMPORT'
};
export {
  MODELS
};
