const DS_ENERGY = 'DATA_SOURCE_ENERGY';
const DS_BOOLEAN = 'DATA_SOURCE_BOOLEAN';
const DS_ENUM = 'DATA_SOURCE_ENUM';
const DS_INTEGER = 'DATA_SOURCE_INTEGER';
const DS_FLOAT = 'DATA_SOURCE_FLOAT';

module.exports = {
  DS_ENERGY,
  DS_BOOLEAN,
  DS_ENUM,
  DS_INTEGER,
  DS_FLOAT
}