import React from 'react';
import CustomNode from "./CustomNode";
export default {
  automaticRearrangeAfterDropNode: false,
  collapsible: false,
  height: 400,
  highlightDegree: 1,
  highlightOpacity: 0.2,
  linkHighlightBehavior: true,
  maxZoom: 3,
  minZoom: 0.5,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  width: 800,
  directed: true,
  node: {
    fontColor: "black",
    fontSize: 10,
    fontWeight: "normal",
    highlightColor: "red",
    highlightFontSize: 10,
    highlightFontWeight: "bold",
    highlightStrokeColor: "SAME",
    highlightStrokeWidth: 1.5,
    mouseCursor: "pointer",
    opacity: 1,
    renderLabel: false,
    size: 400,
    strokeColor: "none",
    strokeWidth: 1,
    svg: "",
    symbolType: "circle",
    viewGenerator: (node) => <CustomNode data={node} />,
  },
  link: {
    color: "#d3d3d3",
    opacity: 1,
    semanticStrokeWidth: false,
    strokeWidth: 2,
    highlightColor: "blue",
    renderLabel: true,
    labelProperty: (link) => link.numberOfData,
  },
};
