// SENSOR BEHAVIOURS
const AB_LOW_ENERGY = 'AB_LOW_ENERGY';
const AB_OUT_OF_ENERGY = 'AB_OUT_OF_ENERGY';
const AB_NODE_FAILED = 'AB_NODE_FAILED';
const AB_SLOW_DOS_ATTACK = 'AB_SLOW_DOS_ATTACK';
const AB_DOS_ATTACK = 'AB_DOS_ATTACK';
// DATA SOURCE BEHAVIOURS
const AB_FIX_VALUE = 'AB_FIX_VALUE';
const AB_INVALID_VALUE = 'AB_INVALID_VALUE';
const AB_VALUE_OUT_OF_RANGE = 'AB_VALUE_OUT_OF_RANGE';
const AB_VALUE_OUT_OF_REGULAR_RANGE = 'AB_VALUE_OUT_OF_REGULAR_RANGE';
const AB_VALUE_CHANGE_OUT_OF_REGULAR_STEP = 'AB_VALUE_CHANGE_OUT_OF_REGULAR_STEP';
const NORMAL_BEHAVIOUR = 'NORMAL_BEHAVIOUR';

module.exports = {
  NORMAL_BEHAVIOUR,
  AB_LOW_ENERGY,
  AB_OUT_OF_ENERGY,
  AB_NODE_FAILED,
  AB_SLOW_DOS_ATTACK,
  AB_DOS_ATTACK,
  AB_FIX_VALUE,
  AB_INVALID_VALUE,
  AB_VALUE_OUT_OF_RANGE,
  AB_VALUE_OUT_OF_REGULAR_RANGE,
  AB_VALUE_CHANGE_OUT_OF_REGULAR_STEP
}