const ONLINE = 'ONLINE';
const OFFLINE = 'OFFLINE';
const SIMULATING = 'SIMULATING';
const PAUSE = 'PAUSE';
const STOP = 'STOP';
const INITIALIZED = 'INITIALIZED';

module.exports = {
  ONLINE,
  OFFLINE,
  SIMULATING,
  PAUSE,
  STOP,
  INITIALIZED
}