const Thing = require("../things/Thing");

/**
 * Simulation class presents a simulation
 */
class Simulation {
  constructor(model, options = null) {
    this.model = model;
    this.newDataset = model.newDataset;
    this.dataStorage = model.dataStorage;
    this.datasetId = model.datasetId;
    this.replayOptions = model.replayOptions;
    this.testCampaignId = model.testCampaignId;
    if (options) {
      // Overwrite the value of datastorage, datasetid and new dataset
      if (options.dataStorage) this.dataStorage = options.dataStorage;
      if (options.datasetId) this.datasetId = options.datasetId;
      if (options.replayOptions) this.replayOptions = options.replayOptions;
      if (options.newDataset) this.newDataset = options.newDataset;
      if (options.testCampaignId) this.testCampaignId = options.testCampaignId;
    }

    // Create the dataset if needed
    const currentTime = Date.now();
    if (!this.newDataset) {
      // use a template for dataset -> all the simulated data should be stored in the data storage
      this.newDataset = {
        id: `data-set-${currentTime}`,
        name: `Dataset of model ${model.name} (${currentTime})`,
        description: `Dataset Generated by model ${
          model.name
        } at time ${new Date(currentTime).toLocaleTimeString()}`,
        tags: ["auto-created"],
        lastModified: currentTime,
        source: "GENERATED",
      };
    } else {
      this.newDataset["lastModified"] = currentTime;
      if (!this.newDataset["source"]) this.newDataset["source"] = "GENERATED";
    }

    // Generate the report
    const currenTime = Date.now();
    let startTime  = 0;
    let endTime = currenTime;
    if (this.replayOptions) {
      if (this.replayOptions.startTime) startTime = this.replayOptions.startTime;
      if (this.replayOptions.endTime) endTime = this.replayOptions.endTime;
    };
    const reportId = `${this.datasetId}-${this.newDataset.id}-${currentTime}`;
    this.report = {
      id: reportId,
      testCampaignId: this.testCampaignId,
      topologyFileName: `${model.name}.json`,
      originalDatasetId: this.datasetId,
      newDatasetId: this.newDataset.id,
      createdAt: currenTime,
      startTime: startTime,
      endTime: endTime,
      score: 0,
    };

    this.allThings = [];
  }

  createDevice(devConfig, isFirstDevice = false) {
    const newThing = new Thing(
      devConfig,
      this.dataStorage,
      this.datasetId,
      this.replayOptions,
      this.newDataset,
      this.report,
      isFirstDevice
    );

    newThing.initDevice(() => {
      newThing.start();
      this.allThings.push(newThing);
    });
  }

  start() {
    console.log("Start simulating for the model: ", this.model.name);
    while (this.allThings.length > 0) {
      this.allThings.pop();
    }
    const { devices } = this.model;
    for (let index = 0; index < devices.length; index++) {
      const dev = devices[index];
      const { id, name, scale, enable } = dev;
      if (enable === false) continue; // skip this device
      let nbDevices = scale ? scale : 1;
      if (nbDevices === 1) {
        this.createDevice(dev, index === 0);
        // NOTE: All the information in the model will be transfer to each Device -> better in the future if we want to improve the performance by parallel the process
      } else {
        for (let tIndex = 0; tIndex < nbDevices; tIndex++) {
          const tID = `${id}-${tIndex}`;
          const tName = `${name}-${tIndex}`;
          this.createDevice({
            ...dev,
            id: tID,
            name: tName,
          }, index === 0 && tIndex === 0);
        }
      }
    }
  }

  /**
   * Stop the simulation
   */
  stop() {
    for (let index = 0; index < this.allThings.length; index++) {
      const th = this.allThings[index];
      th.stop();
    }
  }

  getStats() {
    const stats = [];
    if (!this.allThings) return null;
    for (let index = 0; index < this.allThings.length; index++) {
      const thing = this.allThings[index];
      const thingStats = thing.getStats();
      if (thingStats) stats.push(thingStats);
    }
    return stats;
  }
}

module.exports = Simulation;
