name: Creating a new TaS docker image

on:
  push:
    tags: ["v*"] # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Initialize variables
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        cat <<EOF >> $GITHUB_ENV
        PACKAGE_VERSION=$(echo $GITHUB_REF | tr -d 'refs/tags/' )
        EOF

    - name: Build Docker Image
      run: docker build -t ghcr.io/montimage/tas:${{ env.PACKAGE_VERSION }}


    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/montimage/tas:${{ env.PACKAGE_VERSION }}